spring.application.name=shop-service
spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

resilience4j.circuitbreaker.instances.walletService.sliding-window-size=4
resilience4j.circuitbreaker.instances.walletService.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.walletService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.walletService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.walletService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.walletService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=4
resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always

jwt.secret=YOUR_JWT_SECRET_KEY
cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_API_KEY
cloudinary.api-secret=YOUR_API_SECRET