spring.application.name=api-gateway
server.port=8765

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=wallet-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://wallet-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/wallet-api/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.parts=1

spring.cloud.gateway.server.webflux.routes[1].id=shop-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://shop-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/shop-api/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.parts=1

spring.cloud.gateway.server.webflux.routes[2].id=inventory-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/inventory-api/**
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.parts=1

management.endpoints.web.exposure.include=health,gateway
management.endpoint.health.show-details=always